GET http://localhost:3000/employees
######
DELETE http://localhost:3000/delete-all


############
POST http://localhost:3000/employees
Content-Type: application/json

{
  "id": "fgdsfgsdsdffdf",
  "lastName": "johnjohnjohnjohn",
  "firstName": "johnjohnjohnjohn",
  "department": "ijohnjohnjohnnfo"
}

#####
put http://localhost:3000/check-in
Content-Type: application/json

{
  "employeeId": "65451cf98fddc2598bbd174e",
  "comment": "commentssss"
}

####

put http://localhost:3000/check-out
Content-Type: application/json

{
  "employeeId": "65451cf98fddc2598bbd174e"
}
