GET http://localhost:3000/employees
######
DELETE http://localhost:3000/delete-all


############
POST http://localhost:3000/employees
Content-Type: application/json

{
  "id": "1",
  "lastName": "johnjohnjohnjohn",
  "firstName": "johnjohnjohnjohn",
  "department": "ijohnjohnjohnnfo"
}

#####
post http://localhost:3000/check-in
Content-Type: application/json

{
  "employeeId": "dds",
  "comment": "commentssss"
}

####

post http://localhost:3000/check-out
Content-Type: application/json

{
  "employeeId": "dds"
}
